curriculam/urls.py
from django.urls import path
from curriculam import views

app_name='curriculam'

urlpatterns = [

    path('',views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/',views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/',views.LessionListView.as_view(), name='lession_list'),
    path('<str:standard>/<str:slug>/create/', views.LessionCreateView.as_view(),name='lession_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessionDetailView.as_view(),name='lession_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessionUpdateView.as_view(),name='lession_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessionDeleteView.as_view(),name='lession_delete'),

]

school/urls.py
from django.contrib import admin
from django.urls import path
import app_users
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_users.urls')),
    path('curriculam/',include('curriculam.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/home.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master.css'%}"
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{%url 'index' %}">Home</a>
        <a class="nav-link" href="{%url 'register' %}">Register</a>
        {%if user.is_authenticated %}
        <a class="nav-link" href="{%url 'user_logout' %}">logout</a>
          {% else %}
        <a class="nav-link" href="{%url 'user_login' %}">Login</a>
        {%endif%}
        <a class="nav-link" href="{%url 'curriculam:standard_list' %}">standards</a>
      </div>
    </div>
  </div>
</nav>
<div id=intro class="card text-center">
  <div class="card-header">
    Online School Management System
  </div>
  <div class="card-body">
    <h5 class="card-title">Kommannuthala ZPHS School</h5>

    <br>
    <br>
    


    <a  class="btn btn-primary">Stary Now</a>
  </div>
</div>


        {% block content %}

        {% endblock%}
        <footer class="page-footer" style="background-color:#b2ebf2;">
              <div class="container">
                <div class="row mt-4">
                          <div class="col-md-4 mt-4">
                                    <h3>About Us</h3> <br>
                                    <p>We need to improve little more on fron end</p>
                          </div>
                          <div class="col-md-4 mt-4">
                                    <h3>Other Useful Stuff</h3>
                                    <ul>
                                      <li>Item 1</li>
                                      <li>Item 2</li>
                                      <li>Item 3</li>
                                    </ul>
                          </div>
                          <div class="col-md-4 mt-4">
                                    <h3>Contact Us</h3>
                                    <ul>
                                      <li>Address: komannuthala, kadapa, India</li>
                                      <li>info@gmail.com</li>
                                      <li>contact number</li>
                                    </ul>
                          </div>
                </div>
                <div class="footer-copyright text-center py-3">
                    <p>© 2020 Copyright: Learningbotshub.com</p>
                </div>
              </div>
            </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>