curriculam/urls.py
from django.urls import path
from curriculam import views

app_name='curriculam'

urlpatterns = [

    path('',views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/',views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/',views.LessionListView.as_view(), name='lession_list'),
    path('<str:standard>/<str:slug>/create/', views.LessionCreateView.as_view(),name='lession_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessionDetailView.as_view(),name='lession_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessionUpdateView.as_view(),name='lession_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessionDeleteView.as_view(),name='lession_delete'),

]

school/urls.py
from django.contrib import admin
from django.urls import path
import app_users
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_users.urls')),
    path('curriculam/',include('curriculam.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

curriculam/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Standard(models.Model):
    name=models.CharField(max_length=100,unique=True)
    slug=models.SlugField(null=True, blank=True)
    description=models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
       self.slug=slugify(self.name)
       super().save(*args, **kwargs)


class Subject(models.Model):
    subject_id=models.CharField(max_length=100, unique=True)
    name=models.CharField(max_length=100)
    slug=models.SlugField(null=True, blank=True)
    standard=models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='subjects')
    image=models.ImageField( blank=True, verbose_name='Subject Image')
    description=models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
       self.slug=slugify(self.subject_id)
       super().save(*args, **kwargs)

def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.lesson_id:
        filename = 'lesson_files/{}/{}.{}'.format(instance.lesson_id,instance.lesson_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str('1')
            filename =  'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name, ext)
    return os.path.join(upload_to, filename)

class Lession(models.Model):
    lession_id = models.CharField(max_length=100, unique=True)
    Standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,related_name='lessions')
    name = models.CharField(max_length=250)
    position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    slug = models.SlugField(null=True, blank=True)
    video = models.FileField(upload_to=save_lesson_files,verbose_name="Video", blank=True, null=True)
    ppt = models.FileField(upload_to=save_lesson_files,verbose_name="Presentations", blank=True)
    Notes = models.FileField(upload_to=save_lesson_files,verbose_name="Notes", blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('curriculam:lession_list', kwargs={'slug':self.subject.slug, 'standard':self.Standard.slug})

class Comment(models.Model):
    lession_name = models.ForeignKey(Lession,null=True, on_delete=models.CASCADE,related_name='comments')
    comm_name = models.CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("Comment", null=True, blank=True, on_delete=models.CASCADE,related_name='replies')
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']

class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)

curriculam/forms.py
from django import forms
from curriculam.models import Lession, Comment, Reply


class LessionForm(forms.ModelForm):
    class Meta:
        model = Lession
        fields=('lession_id','name','position','video','ppt','Notes')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

curriculam/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView, ListView, FormView, CreateView,
                  UpdateView, DeleteView)
from curriculam.models import Standard, Subject, Lession, Comment
from curriculam.forms import LessionForm, CommentForm,ReplyForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

# Create your views here.
class StandardListView(ListView):
    context_object_name='standards'
    model= Standard
    template_name='curriculam/standard_list_view.html'

class SubjectListView(DetailView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculam/subject_list_view.html'

class LessionListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculam/lession_list_view.html'

class LessionDetailView(DetailView, FormView):
    context_object_name='lessions'
    model= Lession
    template_name='curriculam/lession_detail_view.html'

    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(LessionDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)
        # context['comments'] = Comment.objects.filter(id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)
        # print("the form name is : ", form)
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculam:lession_detail',kwargs={'standard':standard.slug,
                                                             'subject':subject.slug,
                                                             'slug':self.object.slug})

class LessionCreateView(CreateView):
    form_class = LessionForm
    context_object_name = 'subject'
    model= Subject
    template_name = 'curriculam/lession_create.html'

    def get_success_url(self):
        self.object=self.get_object()
        standard = self.object.standard
        return reverse_lazy('curriculam:lession_list',kwargs={'standard':standard.slug,
                                                               'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object=self.get_object()
        fm=form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class LessionUpdateView(UpdateView):
    fields=('name','position','video','ppt','Notes')
    model=Lession
    template_name='curriculam/lession_update.html'
    context_object_name='lessions'

class LessionDeleteView(DeleteView):
    model= Lession
    context_object_name='lessions'
    template_name='curriculam/lession_delete.html'

    def get_success_url(self):
        print(self.object)
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculam:lession_list',kwargs={'standard':standard.slug,'slug':subject.slug})

templates/curriculam/lession_create.html
{% extends 'home.html'%}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" name="" value="submit">
{% endblock %}

templates/curriculam/lession_delete.html
{% extends 'home.html'%}
{% block content %}
<<h3>Are you surewant to delete ?</h3>
<<form  method="post">
  {% csrf_token %}
  <<input type="submit" name="" value="delete">
    <a href="{% url 'curriculam:lession_detail' standard=lessions.Standard.slug subject=lessions.subject.slug slug=lessions.slug %}">Cancel Delete</a>

</form>
{% endblock%}

templates/curriculam/lession_detail_view.html
{% extends 'home.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}
<p>{{lessions.name}} created on {{lessions.created_at}} by {{lessions.created_by}}</p><br>

<div class="row d-flex justify-content-center mb-3">
      <div id="player-overlay">
            <video controls>
                <source src="{{lessons.video.url}}"  type="video/mp4">
              </video>
      </div>
    </div>
    <br>
      <br>
      <div class="row d-flex justify-content-center mb-3">
            <div id="player-overlay">
                  <video controls>
                      <source src="{{lessons.ppt}}"  type="video/mp4">
                    </video>
            </div>
          </div>
<a class="btn btn-primary" href="{% url 'curriculam:lession_update' standard=lessions.Standard.slug subject=lessions.subject.slug slug=lessions.slug %}" role="button">Update</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-primary" href="{% url 'curriculam:lession_delete' standard=lessions.Standard.slug subject=lessions.subject.slug slug=lessions.slug %}" role="button">Delete</a>

<h2 class="mb-4 mt-5 font-weight-bold" style="color:#ff5722;">Questions And Queries</h2>
    <h4 class="mt-2 font-weight-bold" style="color:#ff5722;">Post your comment or question below:</h4>
    <br><br>
    <div class="container row">
      <div class="col-md-6">
                              <form method="post">
                                    <div class="form-group">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
                                    </div>
                              </form>

      </div>
    </div>
    <div class="row">
      {% for comment in lessions.comments.all %}
      <div class="col-md-8 mt-2 mb-2">
                      <div class="media border p-3">
                          <img src="{% static 'Images/user_avatar.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                          <div class="media-body">
                                    <h4>{{comment.author}} <small><i>Posted on {{comment.date_added}}</i></small></h4>
                                    <p>{{comment.body}}</p>
                            {% for reply in comment.replies.all %}
                                        <div class="media p-3">
                                                <img src="{% static 'Images/user_avatar.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                        <div class="media-body">
                                                <h5>{{reply.author}} <small><i>Posted on {{reply.date_added}}</i></small></h5>
                                                <p>{{reply.reply_body}}</p>
                                          </div>
                                        </div>
                            {% endfor %}
                            <!-- form to post reply -->
                            <form method="post">
                                  <input type="hidden" name="comment.id" value="{{comment.id}}">
                                  <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                  {% csrf_token %}
                                  {{form2.as_p}}
                                  <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
                            </form>

   {% endfor %}

{% endblock %}


<a class="btn btn-primary" href="#" role="button">Link</a>
<a href="{% url 'curriculam:lession_update' standard=lessions.Standard.slug subject=lessions.subject.slug slug=lessions.slug %}"> Update</a>
<a href="{% url 'curriculam:lession_delete' standard=lessions.Standard.slug subject=lessions.subject.slug slug=lessions.slug %}"> delete</a>

templates/curriculam/lession_list_view.html
{% extends 'home.html'%}

{%  block content %}
{% for lession in subjects.lessions.all %}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{lession.name}}</h5>
    <p class="card-text">For {{lession.name}} lession click below</p>
    <a href="{% url 'curriculam:lession_detail' slug=lession.slug subject=subjects.slug standard=lession.Standard.slug %}">Chapter - {{lession.position}}: {{lession.name}}</a><br>
    </div>
</div>
{% endfor %}
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a class="btn btn-primary"   href="{% url 'curriculam:lession_create' standard=subjects.standard.slug slug=subjects.slug %}" role="button">Create lession</a>
{% endblock %}

templates/curriculam/lession_update.html
{% extends 'home.html'%}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" name="" value="submit">
  <a href="{% url 'curriculam:lession_detail' standard=lessions.Standard.slug subject=lessions.subject.slug slug=lessions.slug %}">Cancel Update</a>
{% endblock %}

templates/curriculam/standard_list_view.html
{% extends 'home.html' %}
{% block content %}
<div id="intro1"class="">


  {%for standard in standards %}
  <div class="card">
    <h5 class="card-header">{{standard.name}}</h5>
    <div class="card-body">
      <h5 class="card-title">For {{standard.name}} Class click below</h5>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="{% url 'curriculam:subject_list' slug=standard.slug %}">{{standard.name}} </a>
    </div>
  </div>
  {% endfor %}

  </div>
{% endblock %}

templates/curriculam/sub_list_view.html
{% extends 'home.html' %}

{% block content %}
{%for subject in standards.subjects.all %}
div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">  {{subject.name}}</h5>
        <p class="card-text">{{subject.description}}</p>
      </div>
    </div>
  </div>}
{% endfor %}
{% endblock %}

templates/curriculam/subject_list_view.html
{%  extends 'home.html' %}

{% block content %}
{%for subject in standards.subjects.all %}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{subject.name}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Discription:{{subject.description}} </h6>
    <p class="card-text">For {{subject.name}} claesses click below link</p>
    <a href="{% url 'curriculam:lession_list' slug=subject.slug standard=standards.slug %}">{{subject.name}}</a>
  </div>
</div>

{% endfor %}

{% endblock %}